const settings = {
   // Game Size
   PLAYAREA_WIDTH: 5000,
   PLAYAREA_HEIGHT: 3000,
   // FOOD
   NUM_FOOD: 200,
   NUM_ASTEROIDS: 20,
   NUM_ASTEROID_IMAGES: 4,
   // SHIELDS
   MAX_SHIELD: 1000,
   MAX_SHIELD_REDUCTION: 75,
   BASE_SHIELD: 500,
   //SPEED
   BASE_SPEED: 5,

   BASE_DAMAGE: 75,

   DEBUG_MODE: false,
   SERVER_LOGGING: true,
   DEBUG_MODE_X : 1000,
   DEBUG_MODE_Y : 1000,

  // lvling options
  REGEN_MULTIPLIER : 4,
  DAMAGE_MULTIPLIER : 7,
  SPEED_MULTIPLIER: 1,
  BULLET_SPEED_MULTIPLIER : 10,
};

module.exports= {
  settings
};
